name: Deploy Next.js Messaging App

on:
  push:
    branches:
      - main  # Adjust if needed
  pull_request:
    types:
      - closed  # Runs on merge

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/nextjs-deploy

            git remote set-url origin https://${{ secrets.PAT }}@github.com/VladChira/ip-messaging-web

            echo "Pulling latest changes..."
            git reset --hard
            git pull origin main

            echo "Rebuilding and restarting the container..."
            docker compose down
            docker compose up -d --build --force-recreate

            echo "Deployment complete!"
